activation: gelu
alias: null
attn_dropout: 0.0
batch_normalization: false
batch_size: 64
dataloader_kwargs: null
drop_last_loader: false
dropout: 0.2
early_stop_patience_steps: -1
encoder_layers: 3
exclude_insample_y: false
fc_dropout: 0.2
futr_exog_list: null
h: 4
h_train: 1
head_dropout: 0.0
hidden_size: 256
hist_exog_list: null
inference_input_size: 8
inference_windows_batch_size: 1024
input_size: 8
learn_pos_embed: true
learning_rate: 0.0002253287195129293
linear_hidden_size: 256
loss: &id001 !!python/object:neuralforecast.losses.pytorch.MQLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: {}
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: {}
  _non_persistent_buffers_set: !!set {}
  _parameters:
    quantiles: !!python/object/apply:torch._utils._rebuild_parameter
    - !!python/object/apply:torch._utils._rebuild_tensor_v2
      - !!python/object/apply:torch.storage._load_from_bytes
        - !!binary |
          gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
          AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
          aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
          Z2UKcQFYDgAAADk0NDgzMDEzMTM0OTEycQJYAwAAAGNwdXEDSwVOdHEEUS6AAl1xAFgOAAAAOTQ0
          ODMwMTMxMzQ5MTJxAWEuBQAAAAAAAAAAAAA/zczMPM3MzD1mZmY/mpl5Pw==
      - 0
      - !!python/tuple
        - 5
      - !!python/tuple
        - 1
      - false
      - !!python/object/apply:collections.OrderedDict
        - []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - -median
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADkAAAA1AAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGwAAABvAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADgAAAAwAAAA
  - !!python/object/apply:numpy.core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - U6
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - 24
      - 4
      - 8
    - !!binary |
      LQAAAGgAAABpAAAALQAAADkAAAA1AAAA
  outputsize_multiplier: 5
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 5000
n_heads: 4
n_samples: 100
n_series: 1
num_lr_decays: -1
optimizer: null
optimizer_kwargs: null
patch_len: 16
random_seed: 2
res_attention: true
revin: false
revin_affine: false
revin_subtract_last: true
scaler_type: robust
start_padding_enabled: false
stat_exog_list: null
step_size: 1
stride: 8
val_check_steps: 100
valid_batch_size: null
valid_loss: *id001
windows_batch_size: 512
